# Generated by Django 5.1.1 on 2025-08-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeuser',
            name='passw',
            field=models.CharField(default='open12', max_length=256, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='email_addr',
            field=models.EmailField(max_length=64, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='passw',
            field=models.CharField(default='open12', max_length=256, verbose_name='Password'),
        ),
    ]
