# Generated by Django 5.1.1 on 2025-08-25 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Agency Name')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Agency Address')),
            ],
            options={
                'db_table': 'agency',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=128, unique=True, verbose_name='Document Type')),
            ],
            options={
                'db_table': 'doc_type',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=64, verbose_name='Document ID')),
                ('last_accessed_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last Accessed')),
                ('issuing_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.agency')),
                ('last_accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.policeuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.publicuser')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.documenttype')),
            ],
            options={
                'db_table': 'document',
                'ordering': ('owner', 'issuing_agency', 'document_type', 'document_id'),
            },
        ),
    ]
