# Generated by Django 5.1.1 on 2025-08-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Agency Name')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Agency Address')),
            ],
            options={
                'db_table': 'agency',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=128, unique=True, verbose_name='Document Type')),
            ],
            options={
                'db_table': 'doc_type',
            },
        ),
    ]
