# Generated by Django 5.1.1 on 2025-08-27 18:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_portal', '0001_initial'),
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=64, verbose_name='Document ID')),
                ('ver_status', models.BooleanField(blank=True, default=False, verbose_name='Is Verified')),
                ('verified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='When Verified')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document_portal.documenttype')),
                ('issuing_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document_portal.agency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_portal.publicuser')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_portal.policeuser')),
            ],
            options={
                'db_table': 'ver_document',
            },
        ),
    ]
