# Generated by Django 5.1.1 on 2025-08-27 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_portal', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='When Submitted'),
        ),
    ]
