# Generated by Django 4.1.4 on 2023-08-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action_taken", models.CharField(max_length=499)),
                ("log_type", models.CharField(max_length=16)),
                ("user", models.CharField(max_length=128)),
                ("when_done", models.DateTimeField()),
                ("log_session_id", models.CharField(max_length=255)),
                ("mac_address", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "app_log",
                "ordering": ["log_session_id"],
                "managed": False,
            },
        ),
    ]
