# Generated by Django 4.1.4 on 2024-07-23 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, verbose_name="User")),
                (
                    "session",
                    models.CharField(max_length=1024, verbose_name="Session ID"),
                ),
                (
                    "logged_in",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 23, 16, 11, 48, 15569),
                        verbose_name="User Logged In On",
                    ),
                ),
                ("logged_out", models.DateTimeField(verbose_name="User Logged Out On")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "db_table": "user_log",
                "ordering": ["username", "is_active"],
            },
        ),
    ]
