# Generated by Django 4.1.4 on 2024-07-23 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_userlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="last_active",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 23, 17, 0, 45, 722826),
                null=True,
                verbose_name="Last Active",
            ),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="logged_in",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 23, 17, 0, 45, 722826),
                verbose_name="User Logged In On",
            ),
        ),
    ]
