# Generated by Django 4.1.4 on 2024-07-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0003_userlog_last_active_alter_userlog_logged_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="last_active",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 23, 17, 2, 16, 877161),
                null=True,
                verbose_name="Last Active",
            ),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="logged_in",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 23, 17, 2, 16, 877161),
                verbose_name="User Logged In On",
            ),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="logged_out",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="User Logged Out On"
            ),
        ),
    ]
