# Generated by Django 4.1.4 on 2024-07-24 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0004_alter_userlog_last_active_alter_userlog_logged_in_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlog",
            options={"managed": False, "ordering": ["username", "is_active"]},
        ),
    ]
