# Generated by Django 4.1.4 on 2024-08-23 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0005_alter_userlog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlog",
            options={},
        ),
    ]
