# Generated by Django 4.1.4 on 2024-08-27 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0006_alter_userlog_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlog",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="last_active",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="logged_in",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="logged_out",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="session",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="username",
        ),
        migrations.AlterModelTable(
            name="userlog",
            table=None,
        ),
    ]
