# Generated by Django 4.1.4 on 2024-08-27 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0007_remove_userlog_is_active_remove_userlog_last_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlog",
            options={"managed": False},
        ),
    ]
