# Generated by Django 5.1.1 on 2025-08-25 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=32, verbose_name='First Name')),
                ('oth_names', models.CharField(max_length=128, verbose_name='Other Names')),
                ('lname', models.CharField(max_length=64, verbose_name='Surname')),
                ('reg_num', models.CharField(max_length=32, unique=True, verbose_name='Regulation Number')),
            ],
            options={
                'verbose_name': 'Police User',
                'verbose_name_plural': 'Police Users',
                'db_table': 'pol_user',
                'ordering': ('lname', 'fname', 'reg_num'),
            },
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=32, verbose_name='First Name')),
                ('oth_names', models.CharField(max_length=128, verbose_name='Other Names')),
                ('lname', models.CharField(max_length=64, verbose_name='Surname')),
                ('uid', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Owner ID')),
                ('added_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='When Added')),
            ],
            options={
                'verbose_name': 'Document Owner',
                'verbose_name_plural': 'Document Owners',
                'db_table': 'pub_user',
                'ordering': ('fname', 'lname', 'oth_names'),
            },
        ),
    ]
